# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sarah Griffith's academic webpage
email: sarah_griffith@brown.edu
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/SeaGriff.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/SeaGriff/SeaGriff.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  seagriff

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name   : "Sarah Griffith"
  avatar : "/assets/images/vamos_matroid.svg"
  bio    : "Algebraic geometer and combinatoricist."
  links:
    - label: "University Email"
      icon: ""
      url: "mailto:sarah_griffith@brown.edu"
    - label: "Math Blog"
      icon: ""
      url: "https://sheafifiedsarah.wordpress.com/"
    - label: "GitHub"
      icon: "/assets/github_icon.png"
      url: "https://github.com/SeaGriff"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false